// <auto-generated />
using System;
using InventoryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementSystem.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Computer Accessories",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2424),
                            CurrentStock = 50,
                            Description = "Ergonomic wireless mouse with USB receiver",
                            LowStockThreshold = 10,
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2425),
                            Name = "Wireless Mouse",
                            SKU = "WM-001",
                            SupplierId = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Computer Accessories",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2429),
                            CurrentStock = 30,
                            Description = "RGB mechanical gaming keyboard",
                            LowStockThreshold = 5,
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2430),
                            Name = "Mechanical Keyboard",
                            SKU = "KB-002",
                            SupplierId = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Cables",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2434),
                            CurrentStock = 100,
                            Description = "6ft USB-C to USB-C cable",
                            LowStockThreshold = 20,
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2434),
                            Name = "USB-C Cable",
                            SKU = "CBL-003",
                            SupplierId = 3,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Office Supplies",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2438),
                            CurrentStock = 5,
                            Description = "500 sheets, 80gsm white paper",
                            LowStockThreshold = 15,
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2439),
                            Name = "A4 Printer Paper",
                            SKU = "PPR-004",
                            SupplierId = 2,
                            UnitPrice = 8.99m
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Office Supplies",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2442),
                            CurrentStock = 25,
                            Description = "Blue ink ballpoint pens",
                            LowStockThreshold = 10,
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2442),
                            Name = "Ballpoint Pens (Box of 12)",
                            SKU = "PEN-005",
                            SupplierId = 2,
                            UnitPrice = 5.99m
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Data.Entities.StockMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockAfterMovement")
                        .HasColumnType("int");

                    b.HasKey("MovementId");

                    b.HasIndex("MovementDate");

                    b.HasIndex("MovementType");

                    b.HasIndex("ProductId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("InventoryManagementSystem.Data.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SupplierId");

                    b.HasIndex("Name");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "123 Tech Ave, Silicon Valley, CA 94025",
                            ContactPerson = "John Smith",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2280),
                            Email = "john.smith@techdist.com",
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2280),
                            Name = "Tech Distributors Inc.",
                            Phone = "+1-555-0101"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "456 Business Blvd, New York, NY 10001",
                            ContactPerson = "Sarah Johnson",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2284),
                            Email = "sarah.j@officesupplies.com",
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2285),
                            Name = "Office Supplies Co.",
                            Phone = "+1-555-0102"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "789 Electronics Way, Austin, TX 78701",
                            ContactPerson = "Michael Chen",
                            CreatedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2288),
                            Email = "m.chen@globalelec.com",
                            ModifiedDate = new DateTime(2026, 2, 10, 3, 59, 38, 826, DateTimeKind.Local).AddTicks(2288),
                            Name = "Global Electronics Ltd.",
                            Phone = "+1-555-0103"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Data.Entities.Product", b =>
                {
                    b.HasOne("InventoryManagementSystem.Data.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryManagementSystem.Data.Entities.StockMovement", b =>
                {
                    b.HasOne("InventoryManagementSystem.Data.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryManagementSystem.Data.Entities.Product", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("InventoryManagementSystem.Data.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
